image: ruby:2.5.1

services:
  - postgres:latest

variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

tests:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y nodejs
    - bundle install --without postgres production --jobs $(nproc) "${FLAGS[@]}"
    - cp config/gitlab-database.yml config/database.yml
    - RAILS_ENV=test bundle exec rails db:create db:schema:load
    - bundle exec rails test

staging:
  stage: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=dick-blog-staging --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master
